spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toandfrom?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 0000
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  web:
    cors:
      mappings:
        "[/api/**]":
          allowed-origins: "http://localhost:5173"
          allowed-methods: "*"
          allowed-headers: "*"
          allow-credentials: true

# Flask API 설정
flask:
  api:
    url: http://localhost:5000

server:
  port: 8080
